export declare const CHAR = "utf8";
export declare const DIR_CONFIG_LINUX: string;
export declare const DIR_CONFIG_MAC: string;
export declare const DIR_CONFIG_WIN: string;
export declare const DIR_HOME: string;
export declare const EXT_CHROME = "chromeExtension";
export declare const EXT_WEB = "webExtension";
export declare const INDENT = 2;
export declare const IS_MAC: boolean;
export declare const IS_WIN: boolean;
