export const values: Map<any, any>;
export function abortSetup(msg: string): void;
export function handleSetupCallback(): Function | null;
export function handleRegClose(code: number): Function | null;
export function handleRegStderr(data: any): Function;
export function getBrowserData(key: string): object;
export function getConfigDir(opt?: object): string;
export class Setup {
    constructor(opt?: {
        browser?: string;
        configPath?: string;
        hostDescription?: string;
        hostName?: string;
        mainScriptFile?: string;
        chromeExtensionIds?: any[];
        webExtensionIds?: any[];
        callback?: Function;
        overwriteConfig?: boolean;
    });
    set browser(arg: any);
    get browser(): any;
    set supportedBrowsers(arg: any[]);
    get supportedBrowsers(): any[];
    set configPath(arg: string);
    get configPath(): string;
    set hostDescription(arg: string);
    get hostDescription(): string;
    set hostName(arg: string);
    get hostName(): string;
    set mainScriptFile(arg: string);
    get mainScriptFile(): string;
    set chromeExtensionIds(arg: any[]);
    get chromeExtensionIds(): any[];
    set webExtensionIds(arg: any[]);
    get webExtensionIds(): any[];
    set callback(arg: Function);
    get callback(): Function;
    set overwriteConfig(arg: boolean);
    get overwriteConfig(): boolean;
    _getBrowserConfigDir(): string | null;
    _createReg(manifestPath: string): object;
    _createManifest(shellPath: string, configDir: string): string;
    _createShellScript(configDir: string): string;
    _createConfigDir(): string;
    _createFiles(): Function;
    _handleBrowserConfigDir(): Function;
    _handleBrowserInput(arr: string): Function;
    run(): Function;
    #private;
}
