language: node_js
dist: trusty

os:
  - linux
  - osx
  - windows

node_js:
  - "node"
  - "lts/*"
  - "12"
  - "10"

before_script:
  - npm install

script:
  - npm run lint
  - npm test

jobs:
  exclude:
    - os: osx
      node_js: "12"
    - os: windows
      node_js: "12"
    - os: osx
      node_js: "10"
    - os: windows
      node_js: "10"
